version: '3.1'

services:
  web:
    build: .
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/reise
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reise
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
