"""update  bd 

Revision ID: 2b2b5f038846
Revises: 2d2f2c3c488f
Create Date: 2024-10-22 01:47:15.679942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b2b5f038846'
down_revision: Union[str, None] = '2d2f2c3c488f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tags', ['name'])
    op.drop_constraint('tags_post_id_fkey', 'tags', type_='foreignkey')
    op.drop_column('tags', 'post_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tags_post_id_fkey', 'tags', 'posts', ['post_id'], ['id'])
    op.drop_constraint(None, 'tags', type_='unique')
    # ### end Alembic commands ###
